version: '3.8'

services:
  backend-worker:
    build: src
    image: dmagma-fuzz-backend
    container_name: backend-worker
    environment:
      SHARED_VOLUME: ${SHARED_VOLUME}
      SHARED_PATH: ${SHARED_PATH}
      USER: user
      BROKER_HOST: tasks-broker
      BROKER_USER: ${BROKER_USER}
      BROKER_PASS: ${BROKER_PASS}
      REDIS_HOST: tasks-result
      S3_ENDPOINT: s3
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SHARED_VOLUME}:${SHARED_PATH}
    command: ./run-fuzzing-worker.sh
    depends_on:
      - tasks-broker
      - tasks-result

  tasks-broker:
    image: rabbitmq:3.9-management-alpine
    container_name: tasks-broker
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: ${BROKER_USER}
      RABBITMQ_DEFAULT_PASS: ${BROKER_PASS}

  tasks-result:
    image: redis:alpine
    container_name: tasks-result
    ports:
      - '6379:6379'

  tasks-monitor:
    image: mher/flower
    container_name: tasks-monitor
    ports:
      - '5555:5555'
    environment:
      CELERY_BROKER_URL: amqp://${BROKER_USER}:${BROKER_PASS}@tasks-broker:5672
      CELERY_RESULT_BACKEND: redis://tasks-result
    depends_on:
      - tasks-broker
      - tasks-result

  s3:
    image: minio/minio
    container_name: s3
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server /data --console-address ":9001"

volumes:
  shared-workdir-volume:
    name: ${SHARED_VOLUME}