name: tests

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env: 
  SHARED_VOLUME: shared-workdir-volume
  SHARED_PATH: /shared-workdir
  BROKER_USER: guest
  BROKER_PASS: guest
  S3_ACCESS_KEY: access_key
  S3_SECRET_KEY: secret_key
  CLEAR_CACHE: 1 

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        name: Check out repository
        with:
          submodules: recursive

      - name: Install Python dependencies
        run: |
          cd src
          pip install -r requirements.txt -r requirements.dev.txt

      - name: Bootstrap stack
        run: docker compose up -d tasks-broker tasks-result s3 fuzzing-worker general-worker

      - name: Test services
        run: |
          cd src
          pytest -vvv -m "not celery" --cov backend --cov-report=xml

      - uses: codecov/codecov-action@v3
        with:
          directory: src
          verbose: true

      - name: Test tasks
        run: |
          cd src
          pytest -vvv -m "celery"

      - name: Show logs
        if: ${{ failure() }}
        run: docker compose logs